In [ ]:
import requests
import pandas as pd

def get_api_data():
  response = requests.get ('https://jsonplaceholder.typicode.com/posts/1')
  data = response.json()
  print("Raw API response:", data)
  df = pd.DataFrame([data])
  print("\nDataFrame created from API response:")
  display(df)
  df.shape
  return df

get_api_data()

Raw API response: {'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

DataFrame created from API response:

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...

Fetched 100 posts from the API.

DataFrame of all posts (first 5 rows):

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [ ]:
import requests

API_KEY = "9ae0084092252a38711def6a240792d8"
BASE_URL = "https://api.openweathermap.org/data/2.5/weather"

city = input("Enter city name: ").strip()

response = requests.get(
    url=BASE_URL,
    params={
        "q": city,
        "appid": API_KEY,
        "units": "metric",
    }
)

print(f"\nStatus Code : {response.status_code}")
print(f"URL Called  : {response.url}\n")

if response.status_code == 200:
    data = response.json()

    print(f"City        : {data['name']}, {data['sys']['country']}")
    print(f"Condition   : {data['weather'][0]['description'].capitalize()}")
    print(f"Temperature : {round(data['main']['temp'])}°C")
    print(f"Feels Like  : {round(data['main']['feels_like'])}°C")
    print(f"Humidity    : {data['main']['humidity']}%")
    print(f"Wind Speed  : {data['wind']['speed']} m/s")
    print(f"Pressure    : {data['main']['pressure']} hPa")
    print(f"Visibility  : {data.get('visibility', 0) / 1000:.1f} km")

else:
    error = response.json()
    print(f"Error {response.status_code}: {error.get('message', 'Something went wrong')}")

Enter city name: delhi

Status Code : 200
URL Called  : https://api.openweathermap.org/data/2.5/weather?q=delhi&appid=9ae0084092252a38711def6a240792d8&units=metric

City        : Delhi, IN
Condition   : Clear sky
Temperature : 42°C
Feels Like  : 42°C
Humidity    : 19%
Wind Speed  : 4.12 m/s
Pressure    : 998 hPa
Visibility  : 6.0 km